### ISSUE TITLE
Unable to limit results when using pagination

### ISSUE THREAD

**Issue by philgwynne** [mustasj/expanded-search#1]
Please see issue here: [https://craftcms.stackexchange.com/questions/29925/how-to-limit-expanded-search-plugin-query-results-for-pagination](https://craftcms.stackexchange.com/questions/29925/how-to-limit-expanded-search-plugin-query-results-for-pagination)

**Comment by peirix** [comment]
@mynameisphil Do I understand you correctly in that you'd like to have a `limit` and `offset` on the search result?

**Comment by peirix** [comment]
https://github.com/mustasj/expanded-search/commit/ae3a10fe40cfbbcc529bea1795a8d31ebf78f2b5

Solved by adding `limit` and `offset` as parameters in settings.
