### ISSUE TITLE
Plugin Not Updating in Craft Plugins Store

### ISSUE THREAD

**Issue by philgwynne** [mustasj/expanded-search#2]
Found a new issue where the plugin version updates are not being made available when installed via Craft Plugin Store - which is currently at v.1.1.0. It looks as though the composer file needs the version number adjusting to v1.1.1 as per the guidance here:

[https://docs.craftcms.com/v3/extend/plugin-store.html#plugin-releases](https://docs.craftcms.com/v3/extend/plugin-store.html#plugin-releases)

**Comment by peirix** [comment]
Still learning the plugin ropes. Thanks for the heads up.
