### ISSUE TITLE
BUG: Search doesn't match Craft's default search (too fuzzy)

### ISSUE THREAD

**Issue by alexroper** [mustasj/expanded-search#4]
Craft Default Search Term Options are `subLeft = false` and `subRight = true` ([defaultSearchTermOptions](https://docs.craftcms.com/v3/config/config-settings.html#defaultsearchtermoptions)). It's equivalent to `"$term*"`.

Expanded Search options are using fuzzy searching on either side of the search term:

```php
$entries = Entry::find()
	->search('*' . $term . '*')
	->section($settings->sections)
	->orderBy('score');
```

Also, as a feature request, it would be nice if this could be changed on the fly in templates. Something like this:

```
{% set expandedResults = craft.expandedSearch.search({
    length: 150,
    section: 'blog',
    search: [
      query: searchQuery,
      subLeft: true,
      subRight: true
    ]
}) %}
```

This issue on Github shows the most recent update to the default search options in Craft 3: https://github.com/craftcms/cms/issues/1420

**Comment by peirix** [comment]
I added `subLeft` and `subRight` as settings alongside the query and length. Updated readme shows how to use it.
