### ISSUE TITLE
Filtering on Section ID instead of Section Name

### ISSUE THREAD

**Issue by danleecpi** [mustasj/expanded-search#5]
Hi,

We are trying to restrict site search to particular sections of our website... I know this can be done by section slug but ideally, we need to do this by section ID which works with the Sections Field plugin.

Would it be possible to add sectionId as per the Craft Documentation as an option to filter on in the query?
https://docs.craftcms.com/v3/dev/element-queries/entry-queries.html#sectionid

**Example code for an array of section IDs would be:**

```
// Section ID Array define in the Globals area of Craft
{% set searchSections = siteSearchSettings.siteSearchSections %}

// Updated Expanded Search Code
{% set expandedResults = craft.expandedSearch.search(searchQuery, {
    sectionId: searchSections,
    length: 155,
    offset: (pageInfo.currentPage - 1) * limit,
    limit: limit
}) %}

```

**Comment by peirix** [comment]
Added this feature in 1.3.0. (:
